### ISSUE TITLE
Why angular has been dropped?

### ISSUE THREAD

**Issue by szikszail** [lpolepeddi/made-with-angular#218]
As far as I can see, now the site itself does not use AngularJS. In the past it used AngularJS. Out of my curiosity, was there any reason to drop it?

**Comment by lpolepeddi** [comment]
@szikszail AngularJS is useful for building CRUD apps, and the Made with Angular site just needs the R function. So when I redesigned the site, my thinking in switching away from AngularJS was that I felt I wasn't making use of the stuff that AngularJS is good at to justify using it instead of a static site.

**Comment by szikszail** [comment]
@lpolepeddi Yes, there is a trend to use it for CRUD apps, but as you can see from the wide range of sites you have on the site, not necessary. We have also used it effectively in case of other types of SPA.
Your site is great and it is also nice that it collects pages with AngularJS. It just sounds strange that a page which propagates sites with AngularJS does not use it :)
We have used your site to demonstrate how AngularJS apps could be tested, but because of AngularJS has been dropped, unfortunately, we had to switch to another.
I was just curious about your decision.
Thank you!
